name: publish
on:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: |
          ./gradlew build
      - name: publish
        if: ${{ runner.os == 'Linux' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 6yBwpkox
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          modrinth-dependencies: |
            - confetti-lib
            - fabric-api

          game-versions: |
            [1.21, 1.21.1]

          version-type: release